services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
      - "4576:4576"
    environment:
      - 'LOCALSTACK_HOSTNAME=localhost.localstack.cloud'
      - 'AWS_ACCESS_KEY_ID=localstack'
      - 'AWS_SECRET_ACCESS_KEY=localstack'
      - 'AWS_DEFAULT_REGION=us-east-1'
      - 'SERVICES=sns,sqs'
      - 'DEBUG=${DEBUG-}'
    volumes:
      - ./infra/localstack/setup.sh:/etc/localstack/init/ready.d/setup.sh:ro
      - ./infra/localstack/config:/etc/localstack/init/ready.d/config:ro
      - ./infra/localstack/utils:/etc/localstack/init/ready.d/utils
    networks:
      docker-localstack-network:
        aliases:
          - sns
          - sqs
    restart: unless-stopped
  mongodb:
    container_name: mongodb
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=creditas
      - MONGO_INITDB_ROOT_PASSWORD=creditas
    volumes:
      - ./infra/mongodb/data:/data/db
    networks:
      docker-localstack-network:
        aliases:
          - mongodb
    restart: unless-stopped
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  docker-localstack-network:
    name: docker-localstack-network

volumes:
  influxdb-data:
  grafana-data:
