services:
  localstack:
    image: localstack/localstack:3.3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:6.0.13
    ports:
      - "27017:27017"

