apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-simulator
  template:
    metadata:
      labels:
        app: credit-simulator
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: credit-simulator
          image: credit-simulator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://creditas:creditas@mongo:27017/creditas?authSource=admin&maxPoolSize=100&minPoolSize=10&connectTimeoutMS=1000&socketTimeoutMS=3000&serverSelectionTimeoutMS=3000"
            - name: AWS_ACCESS_KEY_ID
              value: "localstack"
            - name: AWS_SECRET_ACCESS_KEY
              value: "localstack"
            - name: AWS_REGION
              value: "us-east-1"
            - name: CLOUD_AWS_SQS_ENDPOINT
              value: "http://localstack:4566"
            - name: CLOUD_AWS_SNS_ENDPOINT
              value: "http://localstack:4566"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 7000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 7000
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: credit-simulator
spec:
  selector:
    app: credit-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
      nodePort: 30007
  type: ClusterIP # NodePort
