apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-config
data:
  setup.sh: |
    #!/bin/bash
    awslocal sns create-topic --name credit-simulation-events
    awslocal sqs create-queue --queue-name email-notification-queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: localstack
          image: localstack/localstack:latest
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "sqs,sns"
            - name: AWS_ACCESS_KEY_ID
              value: "localstack"
            - name: AWS_SECRET_ACCESS_KEY
              value: "localstack"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
          volumeMounts:
            - name: init
              mountPath: /etc/localstack/init/ready.d
      volumes:
        - name: init
          configMap:
            name: localstack-config
            defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
