apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      initContainers:
        - name: mongo-init-cleanup
          image: mongo:8.0
          command: ["rm", "-f", "/data/db/mongod.lock"]
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
              subPath: db
      containers:
        - name: mongo
          image: mongo:8.0
          args: ["--bind_ip_all"]
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: creditas
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: creditas
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
              subPath: db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32017
